### ISSUE TITLE
Bug with validating passed parameter that can be optional

### ISSUE THREAD

**Issue by dmayo3** [dmayo3/mocksafe#62]
```
Traceback (most recent call last):
  File ".../site-packages/mocksafe/core/mock.py", line 291, in __call__
    return self._spy(*args, **kwargs)
  File ".../site-packages/mocksafe/core/spy.py", line 54, in __call__
    validator.validate()
  File ".../site-packages/mocksafe/core/call_type_validator.py", line 50, in validate
    self._validate_type(param, arg)
  File ".../site-packages/mocksafe/core/call_type_validator.py", line 90, in _validate_type
    raise TypeError(
TypeError: Invalid type passed to mocked method foo() for parameter: 'bar: Optional[Baz]'. Actual argument passed was: SafeMock[Baz#3] (<class 'mocksafe.core.mock.SafeMock'>).
```

**Comment by dmayo3** [comment]
Actually caused by really weird importing causing the arg types to mismatch.
